# Generated by Django 5.2.4 on 2025-07-08 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        help_text="Введите место для привычки",
                        max_length=255,
                        verbose_name="Место привычки",
                    ),
                ),
                (
                    "time",
                    models.TimeField(
                        help_text="Введите время в формате (12:30)",
                        verbose_name="Время выполнения привычки",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Введите действие привычки",
                        max_length=510,
                        verbose_name="Действие привычки",
                    ),
                ),
                (
                    "sign_pleasant_habit",
                    models.BooleanField(verbose_name="Признак приятной привычки"),
                ),
                (
                    "periodicity",
                    models.PositiveIntegerField(
                        choices=[
                            (1, 1),
                            (2, 2),
                            (3, 3),
                            (4, 4),
                            (5, 5),
                            (6, 6),
                            (7, 7),
                        ],
                        default=1,
                        help_text="Выберите период привычки в днях.",
                        verbose_name="Периодичность привычки. в днях",
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True,
                        help_text="Вознаграждение",
                        max_length=255,
                        null=True,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "time_to_complete",
                    models.PositiveIntegerField(
                        help_text="Введите время выполнения привычки (не больше 120сек)",
                        verbose_name="Время на выполнение (не больше 120сек)",
                    ),
                ),
                (
                    "sign_public",
                    models.BooleanField(verbose_name="Признак публичной привычки"),
                ),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="habit_tracker.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
