# Generated by Django 5.2.4 on 2025-07-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habit_tracker", "0002_rename_periodicity_habit_periodicity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="time",
            field=models.DateTimeField(
                help_text="Введите время в формате (2025-01-12 12:30)",
                verbose_name="Время выполнения привычки",
            ),
        ),
    ]
