# Generated by Django 5.2.4 on 2025-07-06 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habit_tracker", "0003_alter_habit_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="time",
            field=models.TimeField(
                help_text="Введите время в формате (12:30)",
                verbose_name="Время выполнения привычки",
            ),
        ),
    ]
